# Generated by Django 5.2.7 on 2025-10-19 00:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_backfill_profiles'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.FileField(blank=True, null=True, upload_to='communities/icons/'),
        ),
        migrations.AddField(
            model_name='category',
            name='moderators',
            field=models.ManyToManyField(blank=True, related_name='moderated_communities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(max_length=60)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='blog.category')),
            ],
            options={
                'unique_together': {('community', 'slug')},
            },
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='posts', to='blog.tag'),
        ),
    ]
