# Generated by Django 5.2.7 on 2025-10-19 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_category_description_category_icon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='active_badge',
            field=models.BooleanField(default=False, help_text='Grant ability to create komunitas without upvotes requirement'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='custom_badge_label',
            field=models.CharField(blank=True, help_text='Optional custom badge label to display on profile', max_length=30),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='custom_badge_style',
            field=models.CharField(blank=True, help_text='Bootstrap color: primary/success/info/warning/danger/secondary', max_length=20),
        ),
    ]
